# Generated by Django 3.1 on 2020-09-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'UNASSIGNED'), (1, 'OPEN'), (2, 'DENY'), (3, 'APPROVE'), (4, 'CLOSE')]),
        ),
    ]
