# Generated by Django 3.1 on 2020-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_processmodel_protype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmodel',
            name='at_leader',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='content',
            field=models.TextField(default='{}'),
        ),
    ]
