# Generated by Django 3.1.1 on 2020-09-09 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20200908_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmodel',
            name='content',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 1, 45, 24, 134006, tzinfo=utc)),
        ),
    ]
