# Generated by Django 3.1.1 on 2020-09-14 00:29

import applications.user.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200824_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'moas_department',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='create',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='head_of_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(null=True, validators=[applications.user.models.PhoneRegexValidator]),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='work_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='workplace',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('42cc6fc8-bad2-483f-b368-babcce5e37cb')),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.departmentmodel'),
        ),
    ]
