# Generated by Django 3.1.1 on 2020-09-14 01:51

import applications.user.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200914_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[applications.user.models.PhoneRegexValidator]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('97e8462d-d62b-4f1c-8c79-ea0f404ae9f6')),
        ),
    ]
