# Generated by Django 3.1.1 on 2020-09-15 01:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200914_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('98d0f40b-bccf-4c52-b1ec-7dae59f8d996')),
        ),
    ]
