# Generated by Django 3.1.1 on 2020-09-15 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200915_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('6ed9bcab-6068-4015-a78f-6be95840c910')),
        ),
    ]
