# Generated by Django 3.1.1 on 2020-09-16 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200915_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('914de002-2c03-42ea-92a6-7309efbc103d')),
        ),
    ]
