# Generated by Django 3.1.1 on 2020-11-12 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200924_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemodel',
            options={'ordering': ('admin', '-id')},
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='role',
            field=models.CharField(default='[]', max_length=512),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('cd721f83-1ab5-4081-9da1-54fde8fc8dfb')),
        ),
    ]
