# Generated by Django 3.1.1 on 2020-11-12 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201112_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='role',
            field=models.CharField(default='[]', max_length=800),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('188bbc78-c878-4886-bb75-55e2f7d7a89c')),
        ),
    ]
