# Generated by Django 3.1.1 on 2020-11-12 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201112_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.rolemodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('6b883695-2036-407c-92f1-6fd79b599d34')),
        ),
    ]
