# Generated by Django 3.1.1 on 2020-11-18 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201112_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemodel',
            options={'ordering': ('-admin', '-id')},
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='role',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('a2c04be7-2cb0-449d-8a91-0610e70a9ca4')),
        ),
    ]
