# Generated by Django 3.1.1 on 2020-11-18 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201118_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('a9f20758-6668-47e5-bd4e-af8710659952')),
        ),
    ]
