# Generated by Django 3.1.1 on 2020-11-19 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201118_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('f8ddf5f7-2c40-4aba-9d40-1b5807cf73e9')),
        ),
    ]
