# Generated by Django 3.1.1 on 2020-10-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_remove_repositorymodel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorymodel',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
