# Generated by Django 3.1.1 on 2020-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_repositorymodel_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorymodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
