# Generated by Django 3.1.1 on 2020-09-14 09:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportmodel',
            unique_together={('person_id', 'date')},
        ),
    ]
