# Generated by Django 3.1.1 on 2020-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200914_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
