# Generated by Django 3.1.1 on 2020-11-17 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_auto_20201009_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=6)),
                ('schedule', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('update', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moas_monthly_report',
                'ordering': ('-update', '-id'),
            },
        ),
    ]
