# Generated by Django 3.1.1 on 2020-11-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_monthlyreportmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreportmodel',
            name='name',
        ),
    ]
