# Generated by Django 3.1.1 on 2020-11-18 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201118_1143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0006_remove_monthlyreportmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportmodel',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.departmentmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlyreportmodel',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
