# Generated by Django 3.1.1 on 2020-11-19 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201119_1013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0007_auto_20201118_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('schedule', models.IntegerField(default=0)),
                ('version', models.CharField(default='0.0.1', max_length=64)),
                ('team', models.CharField(blank=True, max_length=64, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.departmentmodel')),
                ('pertain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moas_subject',
                'ordering': ('-update', '-id'),
            },
        ),
    ]
