# Generated by Django 3.1.1 on 2020-11-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20201119_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='department',
        ),
    ]
