# Generated by Django 3.1.1 on 2020-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_remove_subjectmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='accomplish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='establish',
            field=models.DateField(null=True),
        ),
    ]
