# Generated by Django 3.1.1 on 2020-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20201120_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
