# Generated by Django 3.1.1 on 2020-11-23 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20201120_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionmanagement',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
